### ISSUE TITLE
Deploying statsd-over-slf4j artifact to public Maven repository

### ISSUE THREAD

**Issue by incubos** [nzjess/statsd-over-slf4j#3]
Could you please deploy your artifact to public Maven repository to make it easier to use?

**Comment by nzjess** [comment]
I will try to see if I can upload this to the Sonatype OSS repo

**Comment by incubos** [comment]
Thank you!

**Comment by incubos** [comment]
Any progress?

**Comment by nzjess** [comment]
Have an account on Sonatype now.  Just working out the release / build promotion process.  Shouldn't be too much longer.  Today or tomorrow I hope.  Cheers.

**Comment by nzjess** [comment]
v1.0.0 now available here:  https://oss.sonatype.org/content/repositories/releases/

Have requested sync to central, should happen soon.

Eg:

&lt;dependency&gt;
    &lt;groupId&gt;org.ubercraft.statsd&lt;/groupId&gt;
    &lt;artifactId&gt;statsd-over-slf4j&lt;/artifactId&gt;
    &lt;version&gt;1.0.0&lt;/version&gt;
&lt;/dependency&gt;

**Comment by incubos** [comment]
It's synced. Thanks!
