### ISSUE TITLE
Statsd `ILoggingEvent` doesn't match in `StatsdLogbackAppender.append()`

### ISSUE THREAD

**Issue by incubos** [nzjess/statsd-over-slf4j#5]
You changed `args[1]` to type `Long` in `StatsdLoggerImpl.statArgs()` when implemented https://github.com/nzjess/statsd-over-slf4j/issues/4, but forgot to change `ILoggingEvent` matching code in `StatsdLogbackAppender.append()`. So `StatsdLogbackAppender` doesn't process its events.

I think that we need more test coverage.

By the way, don't you think that `StatsdClient.COUNTER_FORMAT = "%s:%s|c"` should be changed to `COUNTER_FORMAT = "%s:%d|c"`?

**Comment by incubos** [comment]
I suggest using `long` everywhere (for counter and timer values).

**Comment by nzjess** [comment]
Ah, yes.  That's fixed and pushed now.

Open to suggestions on how best to setup a unit test for the appender.
